name: approve

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello this is a simple script

  deploy_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Deploy to Staging
  
  deploy_prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: deploy_staging
    environment: 
      name: Production
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Deploy to Production