name: approve

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello this is a simple script

  deploy_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    environment: Staging
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Deploy to ${{ secrets.NAME }}
  
  deploy_prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: deploy_staging
    environment: Production

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Deploy to ${{ secrets.NAME }}